MACHINE: 2
DEBUG: False
USE_DATA_PARALLEL: True
NUM_CLASSES: 7
SOURCE:
TARGET: 'Mapillary'
RESO: 'LOW'
USE_DEPTH: True
GEN_BINS_IN_CM:
NUM_DEPTH_BINS: 15
SYNTHIA_DATALOADING_MODE: 'original_only'
ENABLE_DISCRIMINATOR: True
DEPTH_PROCESSING: 'DADA'
DEPTH_SAMPLE_TYPE: 'SID'
NUM_WORKERS: 2
NUM_WORKERS_TEST: 2
# dataloader related param
DATA_LIST_SOURCE: 'ctrl/dataset/synthia_list/{}.txt'
DATA_LIST_TARGET: 'ctrl/dataset/mapillary_list/{}.txt'
# model param
IS_MIV3_NEW_ARCH:
CONVERT_PROB_TO_ENTROPY: True

# TRAIN CONFIGS
TRAIN:
    RANDOM_SEED: 1
    SET_SOURCE:
    SET_TARGET: "train"
    DA_METHOD: 'SEMSEG'
    MODEL: 'DeepLabv2'
    MULTI_LEVEL: False
    BATCH_SIZE_SOURCE: 1
    BATCH_SIZE_TARGET: 1
    MAX_ITERS: 90000
    EARLY_STOP: 10000
    POWER: 0.9
    # loss weights
    LAMBDA_SEG: 1.0
    LAMBDA_SRH: 1.0
    LAMBDA_DEPTH: 0.001
    LAMBDA_ADV_MAIN: 0.001
    WEIGHT_DECAY: 0.0005
    # learning rates
    LEARNING_RATE: 0.00025
    LEARNING_RATE_D: 0.0001
    MOMENTUM: 0.9
    EVAL_EVERY: 5000
    SAVE_PRED_EVERY: 1000
    TENSORBOARD_VIZRATE: 1000
    DISPLAY_LOSS_RATE: 50
    SNAPSHOT_DIR:

# TEST CONFIGS
TEST:
    SET_TARGET: "validation"
    MODE: 'best'
    BATCH_SIZE_TARGET: 1

# model weight initialization
WEIGHT_INITIALIZATION:
    DADA_DEEPLABV2:
    RESUME_FROM_SNAPSHOT: True
    RESUME_FROM_SNAPSHOT_GIVEN: # set here the string path for the trained model w/o ISL

# ISL params
TRAIN_ISL_FROM_SCRATCH: True
ISL_THRESHOLD: 0.9
IS_ISL_TRAINING:
NUM_TRAIN_SAMPLES_IN_SOURCE_TARGET: 20
